// <auto-generated />
namespace Mafmax.DepartmentsDirectory.AspNetApp.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class CoreEntitiesCreated : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(CoreEntitiesCreated));
        
        string IMigrationMetadata.Id
        {
            get { return "202106240322480_CoreEntitiesCreated"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
